---
- name: to uninstall apache & httpd
  hosts: all
  become: true
  tasks: 
  - name: Stop httpd
    service: 
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: Uninstall httpd
    yum: 
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"

  - name: stop apache
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstall apache2
    apt: 
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
