--- 
- name: to install apache & httpd service on nodes
  hosts: all
  become: true
  vars:
    port: 8085
  tasks:
  - name: to install httpd pkg
    yum: 
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start apache


  - name: to install apache pkg
    apt: 
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2   
  
  - name: to copy index.html
    copy: 
      src: /opt/index.html
      dest: /var/www/html
      mode: 0666

  - name: Ensure the default Apache port is {{ port }}
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart apache

  - name: Ensure the default Apache port is {{ port }} on ubuntu
    replace:
      path: /etc/apache2/ports.conf
      regexp: '^(Listen[ ]+)[^\n]+$'
      after: "# /etc/apache2/sites-enabled/000-default.conf"
      replace: 'Listen {{ port }}'
    when: ansible_os_family == "Debian"
    notify: restart apache2

  #- name: Ensutle the default Apache port is {{ port  }}  on ubuntu
  #  lineinfile: 
  #    path: /etc/apache2/ports.conf
  #    regexp: '^Listen  '
  #    insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
  #    line: Listen {{ port }}
  #  when: ansible_os_family == "Debian"
  #  notify: restart apache2

  handlers:
  - name: start apache
    service:
      name: httpd
      state: started


  - name: start apache2
    service:
      name: apache2
      state: started

  - name: restart apache
    service:
      name: httpd
      state: restarted 

  - name: restart apache2
    service: 
      name: apache2
      state: restarted
